include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    - avoid_unused_constructor_parameters
    - await_only_futures
    - directives_ordering
    - empty_constructor_bodies
    - empty_statements
    - hash_and_equals
    - implementation_imports
    - null_closures
    - package_api_docs
    - slash_for_doc_comments
    - test_types_in_equals
    - throw_in_finally
    - type_init_formals
